### ISSUE TITLE
Research Queue Options

### ISSUE THREAD

**Issue by MuckT** [healthy-queue/back-end#7]
### Description

Add research here of queue options as a comment.

**Comment by MuckT** [comment]
### [Scaling your Node.js app using distributed queues](https://blog.logrocket.com/scale-node-js-app-using-distributed-queues/)

A good reading about distributed queue options including Bull, Google Pub / Sub, and AWS SQS.

**Comment by MuckT** [comment]
### [Priority Queue using Binary Heap](https://www.geeksforgeeks.org/priority-queue-using-binary-heap/)

A queue which allows adjustments in priority would commonly use a binary heap. This is an example of its implementation.

**Comment by antoni909** [comment]
Libraries: 
- https://docs.bullmq.io/guide/jobs/prioritized

Implement DS: 
- JS Priority Queue <- I vote for this one 
- Example implementation using JS: https://www.geeksforgeeks.org/implementation-priority-queue-javascript/

**Comment by MuckT** [comment]
[Redis](https://www.npmjs.com/package/redis) seems like a good option!

**Comment by MuckT** [comment]
Closed as we ended up our own queue class and queue singleton which can be read more about here: https://github.com/healthy-queue/back-end/pull/35 & https://github.com/healthy-queue/back-end/pull/37.
